- id: '1697756095215'
  alias: Gang beweging
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.gang_sensor_motion
      light_target:
        area_id: gang
- id: kitchen_motion_light
  alias: Keuken Bewegingslicht
  trigger:
  - platform: state
    entity_id: binary_sensor.keuken_sensor_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.keuken_sensor_motion
    to: 'off'
    for:
      minutes: 2
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.keuken_sensor_motion
        state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.keuken
        data: {}
    - conditions:
      - condition: state
        entity_id: binary_sensor.keuken_sensor_motion
        state: 'off'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.keuken
        data: {}
- alias: Flash Red
  trigger:
  - platform: state
    entity_id: input_boolean.flash_red
    to: 'on'
  action:
  - repeat:
      while:
      - condition: state
        entity_id: input_boolean.flash_red
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          entity_id:
          - light.kantoor_plafond
          - light.convectorput
          rgb_color:
          - 255
          - 38
          - 0
      - delay:
          milliseconds: 500
      - service: light.turn_off
        data:
          entity_id:
          - light.kantoor_plafond
          - light.convectorput
      - delay:
          milliseconds: 500
  id: bc98764800ce4ee5887d72d55f956c49
- id: '1697908759181'
  alias: TTS Testen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.tts_test
    to: 'on'
  condition: []
  action:
  - service: tts.google_say
    data:
      cache: false
      entity_id:
      - media_player.slaapkamer_2
      - media_player.slaapkamer
      message: Nina heeft vandaag 3783 stappen gezet. Tijd om naar buiten te gaan!
  mode: single
- alias: Update Dryer Timer
  trigger:
    platform: state
    entity_id: sensor.droger_dryer_completion_time
  action:
  - service: timer.start
    target:
      entity_id: timer.droger_timer
    data:
      duration: '{{ (as_timestamp(strptime(states(''sensor.droger_dryer_completion_time''),
        ''%Y-%m-%dT%H:%M:%S+00:00'')) - as_timestamp(now())) | int }}

        '
  id: d0c1e848ffad4c73a70b00f4333e1910
- id: '1698456877330'
  alias: Welterusten
  description: ''
  trigger:
  - device_id: ef8c38a85b323b90542b3d9ec14251d9
    domain: hue
    platform: device
    type: initial_press
    subtype: 3
    unique_id: 52ae4513-474b-4d98-b642-5946e34fec7d
  condition: []
  action:
  - service: fan.turn_on
    data:
      percentage: 20
    target:
      device_id: 734621e31d54471b4afe95c8ea6feb8e
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: 734621e31d54471b4afe95c8ea6feb8e
    entity_id: 268b6a8b20ba6fd5cc4fb6b791c80dcb
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: fan.oscillate
    data:
      oscillating: true
    target:
      device_id: 734621e31d54471b4afe95c8ea6feb8e
  - device_id: ed1577b84a5e787d05b4a1cf3bf1b1b7
    domain: climate
    entity_id: 43b52ea144d1c384391b5a5d3b34d6b0
    type: set_hvac_mode
    hvac_mode: auto
  - device_id: ed1577b84a5e787d05b4a1cf3bf1b1b7
    domain: climate
    entity_id: 43b52ea144d1c384391b5a5d3b34d6b0
    type: set_preset_mode
    preset_mode: auto
  - device_id: b9b793a04300f80c51eb10be7118ee5e
    domain: climate
    entity_id: b19e1f31ca5ccee59ca1a30185d84575
    type: set_hvac_mode
    hvac_mode: auto
  - device_id: b9b793a04300f80c51eb10be7118ee5e
    domain: climate
    entity_id: b19e1f31ca5ccee59ca1a30185d84575
    type: set_preset_mode
    preset_mode: auto
  mode: single
- id: '1699825461750'
  alias: Lichten Aan bij Beweging na Thuiskomst
  description: Zet lichten aan bij eerste bewegingsdetectie nadat Willem of Nina thuis
    is gekomen
  trigger:
  - platform: state
    entity_id: binary_sensor.gang_sensor_motion
    to: 'on'
  - platform: state
    entity_id:
    - person.willem_spork
    - person.nina_juffermans
    to: home
  condition:
  - condition: state
    entity_id:
    - person.willem_spork
    - person.nina_juffermans
    state: home
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.gang
      - light.woonkamer
      - light.kantoor
    data: {}
  - service: fan.turn_on
    data:
      preset_mode: auto
    target:
      entity_id: fan.huiskamer
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: tts.google_say
    data:
      cache: false
      entity_id:
      - media_player.slaapkamer_2
      - media_player.slaapkamer
      message: Welkom thuis! De temperatuur in huis is {{ states('sensor.gem_woon')
        }} graden.
  mode: single
- id: '1699832305431'
  alias: Temperatuurgebaseerde Welkomstnotificatie
  description: Stuurt een aangepaste welkomstnotificatie gebaseerd op de temperatuur
    in de woonkamer
  trigger:
  action:
  - service: notify.willem
    data:
      message: "{% set temp = states('sensor.gem_woon') | float %} {% if temp < 14
        %}\n  Welkom terug. Het is erg koud in huis! Ik ga het snel opwarmen naar
        18 graden.\n{% elif temp < 18 %}\n  Welkom thuis. De temperatuur is {{ temp
        }} graden. De kachel is aan het opwarmen naar 18 graden.\n{% else %}\n  Welkom
        thuis.\n{% endif %}\n"
  mode: single
- id: '1699833072987'
  alias: Als iedereen van huis is
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.persons
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.nina_juffermans
      state: not_home
    - condition: state
      entity_id: person.willem_spork
      state: not_home
  action:
  - service: fan.turn_off
    data: {}
    target:
      area_id: slaapkamer
  - service: fan.turn_off
    data: {}
    target:
      area_id: woonkamer
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.afwezig_modus
  mode: single
- id: '1700000000000'
  alias: Speel Geselecteerd Radiostation
  description: Speelt het geselecteerde radiostation af in kantoor
  trigger:
  - platform: state
    entity_id: input_select.radio_station
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.slaapkamer
    data:
      media_content_id: "{% set station = states('input_select.radio_station') %}
        {% set stations = {\n  \"QMusic\": \"https://stream.qmusic.nl/qmusic/mp3\",\n
        \ \"BNR Nieuwsradio\": \"https://stream.bnr.nl/bnr_mp3_128_20\",\n  \"QMusic
        Non-Stop\": \"https://stream.qmusic.nl/nonstop/mp3\",\n  \"LoFi\": \"http://streams.dez.ovh:8000/radio.mp3\",\n
        \ \"Efteling Radio\": 'http://ice.cr2.streamzilla.xlcdn.com:8000/sz=efteling=hdstream'\n}
        %} {{ stations[station] }}\n"
      media_content_type: music
  mode: single
