- alias: Flash Red
  trigger:
  - platform: state
    entity_id: input_boolean.flash_red
    to: 'on'
  action:
  - repeat:
      while:
      - condition: state
        entity_id: input_boolean.flash_red
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          entity_id:
          - light.kantoor_plafond
          - light.convectorput
          rgb_color:
          - 255
          - 38
          - 0
      - delay:
          milliseconds: 500
      - service: light.turn_off
        data:
          entity_id:
          - light.kantoor_plafond
          - light.convectorput
      - delay:
          milliseconds: 500
  id: bc98764800ce4ee5887d72d55f956c49
- id: '1697908759181'
  alias: TTS Testen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.tts_test
    to: 'on'
  condition: []
  action:
  - service: tts.google_say
    data:
      cache: false
      entity_id:
      - media_player.slaapkamer_2
      - media_player.slaapkamer
      message: Nina heeft vandaag 3783 stappen gezet. Tijd om naar buiten te gaan!
  mode: single
- alias: Update Dryer Timer
  trigger:
    platform: state
    entity_id: sensor.droger_dryer_completion_time
  action:
  - service: timer.start
    target:
      entity_id: timer.droger_timer
    data:
      duration: '{{ (as_timestamp(strptime(states(''sensor.droger_dryer_completion_time''),
        ''%Y-%m-%dT%H:%M:%S+00:00'')) - as_timestamp(now())) | int }}

        '
  id: d0c1e848ffad4c73a70b00f4333e1910
- id: '1698456877330'
  alias: Welterusten
  description: ''
  triggers:
  - device_id: ef8c38a85b323b90542b3d9ec14251d9
    domain: hue
    type: initial_press
    subtype: 3
    unique_id: 52ae4513-474b-4d98-b642-5946e34fec7d
    trigger: device
  conditions: []
  actions:
  - data:
      percentage: 20
    target:
      device_id: 734621e31d54471b4afe95c8ea6feb8e
    action: fan.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - type: turn_on
    device_id: 734621e31d54471b4afe95c8ea6feb8e
    entity_id: 268b6a8b20ba6fd5cc4fb6b791c80dcb
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - data:
      oscillating: true
    target:
      device_id: 734621e31d54471b4afe95c8ea6feb8e
    action: fan.oscillate
  - device_id: ed1577b84a5e787d05b4a1cf3bf1b1b7
    domain: climate
    entity_id: 43b52ea144d1c384391b5a5d3b34d6b0
    type: set_hvac_mode
    hvac_mode: auto
  - device_id: ed1577b84a5e787d05b4a1cf3bf1b1b7
    domain: climate
    entity_id: 43b52ea144d1c384391b5a5d3b34d6b0
    type: set_preset_mode
    preset_mode: auto
  - device_id: b9b793a04300f80c51eb10be7118ee5e
    domain: climate
    entity_id: b19e1f31ca5ccee59ca1a30185d84575
    type: set_hvac_mode
    hvac_mode: auto
  - device_id: b9b793a04300f80c51eb10be7118ee5e
    domain: climate
    entity_id: b19e1f31ca5ccee59ca1a30185d84575
    type: set_preset_mode
    preset_mode: auto
  - entity_id: all
    action: light.turn_off
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.sleep_mode
    data: {}
  mode: single
- id: '1700000000000'
  alias: Speel Geselecteerd Radiostation
  description: Speelt het geselecteerde radiostation af in kantoor
  trigger:
  - platform: state
    entity_id: input_select.radio_station
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.slaapkamer
    data:
      media_content_id: "{% set station = states('input_select.radio_station') %}
        {% set stations = {\n  \"QMusic\": \"https://stream.qmusic.nl/qmusic/mp3\",\n
        \ \"BNR Nieuwsradio\": \"https://stream.bnr.nl/bnr_mp3_128_20\",\n  \"QMusic
        Non-Stop\": \"https://stream.qmusic.nl/nonstop/mp3\",\n  \"LoFi\": \"http://streams.dez.ovh:8000/radio.mp3\",\n
        \ \"Efteling Radio\": 'http://ice.cr2.streamzilla.xlcdn.com:8000/sz=efteling=hdstream'\n}
        %} {{ stations[station] }}\n"
      media_content_type: music
  mode: single
- id: standard_theme
  alias: 'System: standaard thema selecteren bij herstart'
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  actions:
  - data:
      name: minimalist-ios-tapbar
    action: frontend.set_theme
  initial_state: 'true'
- id: '1729727657788'
  alias: 'Test: PS5 automation'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.ps5_668_activity
    attribute: activity
  - trigger: state
    entity_id:
    - input_boolean.tv_mode
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.ps5_668_activity
      attribute: activity
      state: playing
    - condition: state
      entity_id: input_boolean.tv_mode
      state: 'on'
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ states(''sensor.time'') >= states(''input_datetime.start_tvmodus'')[0:5]
        and states(''sensor.time'') < ''24:00'' }}'
    - condition: template
      value_template: '{{ states(''sensor.time'') >= ''00:00'' and states(''sensor.time'')
        <= states(''input_datetime.end_tvmodus'')[0:5] }}'
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.tv_mode
        state: 'on'
      - condition: state
        entity_id: sensor.ps5_668_activity
        attribute: activity
        state: playing
      sequence:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.adaptive_lighting_adapt_brightness_living_room
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.tv_mode
          state: 'off'
        - condition: not
          conditions:
          - condition: state
            entity_id: sensor.ps5_668_activity
            attribute: activity
            state: playing
      sequence:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.adaptive_lighting_sleep_mode_living_room
  mode: single
- id: '1731366389356'
  alias: Button Living Room Actions
  description: ''
  triggers:
  - entity_id: sensor.living_button_action
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.living_button_action
        state: 1_single_press
      sequence:
      - target:
          area_id: woonkamer
        action: light.turn_on
        data: {}
    - conditions:
      - condition: state
        entity_id: sensor.living_button_action
        state: 2_long_press
      sequence:
      - target:
          area_id: kantoor
        action: light.toggle
        data: {}
    - conditions:
      - condition: state
        entity_id: sensor.living_button_action
        state: 1_long_press
      sequence:
      - target:
          area_id: keuken
        action: light.turn_off
        data: {}
    default: []
  mode: single
- id: '1731367575914'
  alias: 'Button Living Room: toggle tv mode'
  description: ''
  triggers:
  - domain: mqtt
    device_id: 32679cd523b0e0d77da0be6322db3aba
    type: action
    subtype: 1_initial_press
    trigger: device
  conditions: []
  actions:
  - action: input_boolean.toggle
    target:
      entity_id: input_boolean.tv_mode
    data: {}
  mode: single
