#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/

# Load frontend themes from the themes folder

homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /hacsfiles/Bubble-Card/bubble-pop-up.js
http: !include includes/http.yaml
# tts: !include includes/tts.yaml

# Inputs
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetimes.yaml
input_select: !include includes/input_select.yaml
counter: !include includes/counters.yaml

#Logging and history
logger: !include includes/logger.yaml
device_tracker: !include includes/device_tracker.yaml

# Managed via UI
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Others
person: !include includes/persons.yaml
sensor: !include includes/sensor.yaml
group: !include includes/groups.yaml
automation old: !include_dir_merge_list automations
notify: !include includes/notify.yaml
timer: !include includes/timer.yaml
light: !include includes/lights.yaml
zone: !include includes/zones.yaml
binary_sensor: !include includes/binary_sensors.yaml
ios: !include includes/ios.yaml

# Custom integrations
adaptive_lighting: !include includes/adaptive_lighting.yaml