- alias: "iOS: lichten in kantoor aan-/uitzetten"
  initial_state: true
  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: "Kantoor"
  actions:
    - action: light.toggle
      target:
        entity_id: light.kantoor_lampen
