- alias: "iOS: lichten in kantoor aan-/uitzetten"
  initial_state: true
  triggers:
    - trigger: event
      event_type: ios.action_fired
      event_data:
        actionName: "Kantoor"
  actions:
    - service: light.toggle
      entity_id: light.kantoor_lampen