- alias: "Leaving: when everybody leaves the house turn off all lights"
  triggers:
    - trigger: state
      entity_id: group.persons
      to: "not_home"
  actions:
    - service: light.turn_off
      target:
        entity_id: all