#   _      _       _               _____                       
#  | |    (_)     (_)             |  __ \                      
#  | |     ___   ___ _ __   __ _  | |__) |___   ___  _ __ ___  
#  | |    | \ \ / / | '_ \ / _` | |  _  // _ \ / _ \| '_ ` _ \ 
#  | |____| |\ V /| | | | | (_| | | | \ \ (_) | (_) | | | | | |
#  |______|_| \_/ |_|_| |_|\__, | |_|  \_\___/ \___/|_| |_| |_|
#                           __/ |                              
#                          |___/                               



#   _  ___ _       _                
#  | |/ (_) |     | |               
#  | ' / _| |_ ___| |__   ___ _ __  
#  |  < | | __/ __| '_ \ / _ \ '_ \ 
#  | . \| | || (__| | | |  __/ | | |
#  |_|\_\_|\__\___|_| |_|\___|_| |_|
#

- alias: "Lights: turn on kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_kitchen
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.cooking_mode
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.keuken

- alias: "Lights: turn off kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_kitchen
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.cooking_mode
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.keuken

- alias: "Button: Keuken Mode Automation"
  trigger:
    - platform: state
      entity_id: sensor.kitchen_button_action
      to: 'single'
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.cooking_mode

- alias: "Light: Cooking Mode Lighting Control"
  trigger:
    - platform: state
      entity_id: input_boolean.cooking_mode
      to: 'on'
    - platform: state
      entity_id: input_boolean.cooking_mode
      to: 'off'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.cooking_mode
              state: 'on'
          sequence:
            - service: switch.turn_off
              target:
                entity_id: switch.adaptive_lighting_kitchen
            - service: light.turn_on
              target:
                entity_id: light.keuken
              data:
                color_temp: 183
                brightness: 202
        - conditions:
            - condition: state
              entity_id: input_boolean.cooking_mode
              state: 'off'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.adaptive_lighting_kitchen



#   _    _       _ _                     
#  | |  | |     | | |                    
#  | |__| | __ _| | |_      ____ _ _   _ 
#  |  __  |/ _` | | \ \ /\ / / _` | | | |
#  | |  | | (_| | | |\ V  V / (_| | |_| |
#  |_|  |_|\__,_|_|_| \_/\_/ \__,_|\__, |
#                                   __/ |
#                                  |___/ 

- alias: "Lights: turn on when motion detected in the hallway"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_hallway
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.gang

- alias: "Lights: turn off when motion detected in the hallway"
  trigger:
  - platform: state
    entity_id: binary_sensor.activity_in_hallway
    to: 'off'
  action:
  - service: light.turn_off
    entity_id: light.gang

#  __          __           _           _          
#  \ \        / /          | |         | |         
#   \ \  /\  / /_ _ _ __ __| |_ __ ___ | |__   ___ 
#    \ \/  \/ / _` | '__/ _` | '__/ _ \| '_ \ / _ \
#     \  /\  / (_| | | | (_| | | | (_) | |_) |  __/
#      \/  \/ \__,_|_|  \__,_|_|  \___/|_.__/ \___|
                                                 
- alias: "Lights: turn off when stopped motion detected in the hallway"
  trigger:
  - platform: state
    entity_id: binary_sensor.activity_in_hallway
    to: 'off'
    for:
      minutes: 12
  condition:
    - condition: state
      entity_id: light.inloopkast
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.inloopkast

#   ____           _                           
#  |  _ \         | |                          
#  | |_) | ___  __| |_ __ ___   ___  _ __ ___  
#  |  _ < / _ \/ _` | '__/ _ \ / _ \| '_ ` _ \ 
#  | |_) |  __/ (_| | | | (_) | (_) | | | | | |
#  |____/ \___|\__,_|_|  \___/ \___/|_| |_| |_|
                                             
# - alias: "Lights: turn on bedroom"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.someone_in_bedroom
#       to: 'on'
#   action:
#     - service: light.turn_on
#       entity_id: light.slaapkamer

# - alias: "Lights: turn off bedroom"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.someone_in_bedroom
#       to: 'off'
#   action:
#     - delay: '00:00:30'
#     - service: light.turn_off
#       entity_id: light.slaapkamer