# Locationbased notifications
- alias: "Work: Willem left work notification for Nina"
  triggers:
    - trigger: state
      entity_id: person.willem_spork
      from: "Office"
  conditions:
    - condition: time
      after: "15:00:00"
      before: "23:00:00"
  actions:
    - action: notify.all_iphones
      data:
        title: "Work"
        message: "Willem vertrekt van kantoor! ♥️🎉"

- alias: "Work: Nina left work notification for Willem"
  triggers:
    - trigger: state
      entity_id: person.nina_juffermans
      from: "Office"
  conditions:
    - condition: time
      after: "15:00:00"
      before: "23:00:00"
  actions:
    - action: notify.all_iphones
      data:
        title: "Work"
        message: "Nina vertrekt van kantoor! ♥️🎉"

- alias: "Notifications: front door has opened"
  triggers:
    - trigger: state
      entity_id: binary_sensor.voordeur_deur
      to: "on"
  conditions:
    - condition: state
      entity_id: input_boolean.front_door_open_warning
      state: "on"
  actions:
    - action: notify.willem
      data:
        title: Security
        message: Front door opened!
    - action: input_boolean.turn_off
      entity_id: input_boolean.front_door_open_warning

# Household notifications

- alias: "Notifications: put the trash outside"
  description: "Herinnering om de afvalbak naar buiten te zetten op maandagavond om 21:00"
  triggers:
    - trigger: time
      at: "21:00:00"
  conditions:
    - condition: time
      weekday:
        - mon
  actions:
    - action: notify.all_iphones
      data:
        title: "🗑️ Afvalherinnering"
        message: "Denk eraan om de afvalbak buiten te zetten!"
  mode: single

# Hourly mantra's

- alias: "Notifications: Hourly Mantra Notification for Nina"
  triggers:
    - trigger: time_pattern
      hours: "/1"
  conditions:
    - condition: template
      value_template: "{{ not is_state('input_select.sleep_mode', 'total') }}"
  actions:
    - action: notify.nina
      data:
        title: "Hourly Mantra ❤️"
        message: >
          {% set mantras = [
            "Ik ben een mooie vrouw",
            "Ik hoef mezelf niet te bewijzen",
            "Ik ben geliefd",
            "Ik ben het waard",
            "Ik ben goed genoeg",
            "Ik ben een goede moeder",
            "Ik rock mijn carrière en fitnessdoelen met dezelfde passie",
            "Sterk is het nieuwe sexy, en ik ben beide",
            "Mijn energie en drive maken me onstuitbaar op werk en in de sportschool",
            "Elke dag is een nieuwe kans om te shinen, zowel in mijn job als in mijn workout",
            "Ik balanceer werk en fun alsof het niets is",
            "Mijn lichaam is mijn tempel, en ik behandel het als een koningin",
            "Zelfvertrouwen is mijn superkracht, zowel in vergaderingen als tijdens yoga",
            "Ik ben de baas over mijn gezondheid en mijn carrièrepad",
            "Mijn motivatie is net zo sterk als mijn koffie",
            "Ik flirt met succes en het flirt terug",
            "Elke zweetdruppel tijdens de training telt als een stap naar succes",
            "Ik ben mijn eigen cheerleader, in de sportschool en op mijn werk",
            "Mijn glimlach is mijn krachtigste accessoire, altijd en overal",
            "Ik vier elk klein succesje, want ik weet dat ze optellen",
            "Mijn leven is mijn avontuur, vol passie en nieuwe kansen",
            "Ik ben de architect van mijn eigen geluk",
            "Ik verwelkom groei en verandering met een open hart",
            "Mijn innerlijke vrede is onaantastbaar",
            "Ik laat los wat ik niet kan veranderen",
            "Ik kies ervoor om vandaag vreugde te vinden in kleine dingen",
            "Ik ben dankbaar voor de liefde die ik geef en ontvang",
            "Mijn potentieel is onbegrensd",
            "Ik vertrouw op mijn intuïtie en wijsheid",
            "Elke uitdaging is een kans om te groeien",
            "Ik verdien rust en herstel",
            "Ik ben een bron van licht en liefde",
            "Mijn woorden en daden zijn doordrenkt met vriendelijkheid",
            "Ik sta sterk in mijn authenticiteit",
            "Mijn hart is open voor nieuwe mogelijkheden",
            "Ik ben een katalysator voor positieve verandering",
            "Ik erken mijn eigenwaarde en schoonheid",
            "Mijn reis is uniek en waardevol",
            "Ik kies voor gezonde grenzen in al mijn relaties",
            "Ik vier mijn persoonlijke overwinningen, groot en klein",
            "Mijn geluk is een reflectie van mijn innerlijke harmonie",
            "Mijn sensualiteit is mijn kracht",
            "Ik geniet van elke vorm van intimiteit",
            "Mijn lichaam verdient liefde en genot",
            "Ik omarm mijn seksuele energie",
            "Ik ben in harmonie met mijn verlangens",
            "Mijn seksuele expressie is vrij en zelfverzekerd",
            "Ik ben comfortabel in mijn seksualiteit",
            "Mijn seksuele energie is een bron van creativiteit",
            "Ik sta open voor nieuwe seksuele avonturen",
            "Mijn seksuele behoeften zijn waardevol en legitiem",
            "Ik geniet van het ontdekken van mijn seksuele grenzen",
            "Mijn lichaam is een bron van plezier en kracht",
            "Ik vier mijn seksuele vrijheid",
            "Mijn seksualiteit is een belangrijk deel van wie ik ben",
            "Ik ben trots op mijn seksuele zelf"
          ] %}
          {% set mantra = mantras | random %}
          {{ mantra }}

- alias: "Notifications: Hourly Mantra Notification for Willem"
  triggers:
    - trigger: time_pattern
      hours: "/1"
  conditions:
    - condition: template
      value_template: "{{ not is_state('input_select.sleep_mode', 'total') }}"
  actions:
    - action: notify.willem
      data:
        title: "Hourly Mantra 💪"
        message: >
          {% set mantras = [
            "Ik ben sterker dan ik denk",
            "Ik hoef mezelf niet te bewijzen",
            "Ik ben geliefd",
            "Ik ben het waard",
            "Ik ben goed genoeg",
            "Ik ken mijn dromen waar maken",
            "Ik rock mijn carrière en fitnessdoelen met dezelfde passie",
            "Ik mag mijn emoties voelen",
            "Ik heb geen veiligheidsgedrag nodig"
          ] %}
          {% set mantra = mantras | random %}
          {{ mantra }}
